// Code generated by 'fieldr'; DO NOT EDIT.

package asmap

type EmbeddedAddressField string

const (
	ZipCode     EmbeddedAddressField = "ZipCode"
	AddressLine EmbeddedAddressField = "AddressLine"
)

func (v *EmbeddedAddress) AsMap() map[EmbeddedAddressField]interface{} {
	m := map[EmbeddedAddressField]interface{}{}
	m[ZipCode] = v.ZipCode
	m[AddressLine] = v.AddressLine
	return m
}
