// Code generated by 'fieldr'; DO NOT EDIT.

package asmap

type (
	EmbeddedAddressField string
)

const (
	EmbeddedAddressFieldZipCode     EmbeddedAddressField = "ZipCode"
	EmbeddedAddressFieldAddressLine EmbeddedAddressField = "AddressLine"
)

func (v *EmbeddedAddress) AsMap() map[EmbeddedAddressField]interface{} {
	return map[EmbeddedAddressField]interface{}{
		EmbeddedAddressFieldZipCode:     v.ZipCode,
		EmbeddedAddressFieldAddressLine: v.AddressLine,
	}
}
