// Code generated by 'fieldr'; DO NOT EDIT.

package asmap

type (
	StructField string
)

const (
	StructFieldID              = StructField("ID")
	StructFieldTS              = StructField("TS")
	StructFieldName            = StructField("Name")
	StructFieldSurname         = StructField("Surname")
	structFieldNoExport        = StructField("noExport")
	StructFieldNoTag           = StructField("NoTag")
	StructFieldIgnoredInTagMap = StructField("IgnoredInTagMap")
	StructFieldAddress         = StructField("Address")
	StructFieldFlatNoPrefix    = StructField("FlatNoPrefix")
	StructFieldFlatPrefix      = StructField("FlatPrefix")
)

func (v *Struct) AsMap() map[StructField]interface{} {
	return map[StructField]interface{}{
		StructFieldID:              v.ID,
		StructFieldTS:              v.TS,
		StructFieldName:            v.Name,
		StructFieldSurname:         v.Surname,
		StructFieldNoTag:           v.NoTag,
		StructFieldIgnoredInTagMap: v.IgnoredInTagMap,
		StructFieldAddress:         v.Address.AsMap(),
		StructFieldFlatNoPrefix:    v.FlatNoPrefix,
		StructFieldFlatPrefix:      v.FlatPrefix,
	}
}
