// Code generated by 'fieldr'; DO NOT EDIT.

package as_map

type (
	StructField    string
	StructTag      string
	StructTagValue string
)

const (
	structField_ID              = StructField("ID")
	structField_Name            = StructField("Name")
	structField_Surname         = StructField("Surname")
	StructField_noExport        = StructField("noExport")
	structField_NoTag           = StructField("NoTag")
	structField_IgnoredInTagMap = StructField("IgnoredInTagMap")

	StructTag_toMap = StructTag("toMap")

	structTagValue_toMap_ID       = StructTagValue("id")
	structTagValue_toMap_Name     = StructTagValue("name")
	structTagValue_toMap_Surname  = StructTagValue("surname")
	StructTagValue_toMap_noExport = StructTagValue("no_export")
	structTagValue_toMap_NoTag    = StructTagValue("NoTag") //empty tag
)

func (v *Struct) AsMap() map[StructField]interface{} {
	return map[StructField]interface{}{
		structField_ID:              v.ID,
		structField_Name:            v.Name,
		structField_Surname:         v.Surname,
		structField_NoTag:           v.NoTag,
		structField_IgnoredInTagMap: v.IgnoredInTagMap,
	}
}

func (v *Struct) AsTagMap(tag StructTag) map[StructTagValue]interface{} {
	switch tag {
	case StructTag_toMap:
		return map[StructTagValue]interface{}{
			structTagValue_toMap_ID:      v.ID,
			structTagValue_toMap_Name:    v.Name,
			structTagValue_toMap_Surname: v.Surname,
			structTagValue_toMap_NoTag:   v.NoTag,
		}
	}
	return nil
}
