// Code generated by 'const -type TestStruct -tag db'; DO NOT EDIT.

package test

type (
	TestStruct_db string
)

const (
	TestStruct_db_ID   = TestStruct_db("_id")
	TestStruct_db_Name = TestStruct_db("_name")
)
