// Code generated by 'const -type TestStruct'; DO NOT EDIT.

package test

type (
	TestStruct_db   string
	TestStruct_json string
)

const (
	TestStruct_db_ID   = TestStruct_db("_id")
	TestStruct_db_Name = TestStruct_db("_name")

	TestStruct_json_ID = TestStruct_json("ID")
)
