// Code generated by 'fieldr'; DO NOT EDIT.

package enum_const_db

type column string

const (
	colID      column = "id"
	colVersion column = "version"
	colName    column = "name"
	pkID       column = "id"
)

func columns() []column {
	return []column{colID, colVersion, colName}
}

func (s *Entity) ref(f column) any {
	if s == nil {
		return nil
	}
	switch f {
	case colID:
		return &s.BaseEntity.ID
	case colVersion:
		if v := s.Versioned; v != nil {
			return &v.Version
		}
	case colName:
		return &s.Name
	}
	return nil
}

func pk() []column {
	return []column{pkID}
}
