// Code generated by 'fieldr'; DO NOT EDIT.

package builder

import (
	"bytes"
	"example/sql_base"
	"time"
)

type EntityBuilder[ID any, S string] struct {
	ID           ID
	Code         string
	ForeignID    ID
	Schema       string
	Version      int
	NoDB         *NoDBFieldsEntity
	Name         StringBasedType[S]
	Surname      StringBasedAlias
	Values       []int32
	Ts           []*time.Time
	Versioned    sql_base.VersionedEntity
	Chan         chan map[time.Time]string
	SomeMap      map[StringBasedType[string]]bytes.Buffer
	Embedded     EmbeddedEntity
	OldForeignID *ForeignIDAwareEntity[ID]
}

func NewEntityBuilder[ID any, S string]() *EntityBuilder[ID, S] {
	return &EntityBuilder[ID, S]{}
}

func (b *EntityBuilder[ID, S]) Build() *Entity[ID, S] {
	if b == nil {
		return &Entity[ID, S]{}
	}
	return &Entity[ID, S]{
		BaseEntity: &BaseEntity[ID]{
			ID: b.ID,
			RefCodeAwareEntity: &RefCodeAwareEntity{
				CodeAwareEntity: &CodeAwareEntity{
					Code: b.Code,
				},
			},
			ForeignIDAwareEntity: ForeignIDAwareEntity[ID]{
				ForeignID: b.ForeignID,
			},
		},
		Metadata: Metadata{
			Schema:  b.Schema,
			Version: b.Version,
		},
		NoDB:         b.NoDB,
		Name:         b.Name,
		Surname:      b.Surname,
		Values:       b.Values,
		Ts:           b.Ts,
		Versioned:    b.Versioned,
		Chan:         b.Chan,
		SomeMap:      b.SomeMap,
		Embedded:     b.Embedded,
		OldForeignID: b.OldForeignID,
	}
}

func (b *EntityBuilder[ID, S]) SetID(id ID) *EntityBuilder[ID, S] {
	if b != nil {
		b.ID = id
	}
	return b
}

func (b *EntityBuilder[ID, S]) SetCode(code string) *EntityBuilder[ID, S] {
	if b != nil {
		b.Code = code
	}
	return b
}

func (b *EntityBuilder[ID, S]) SetForeignID(foreignID ID) *EntityBuilder[ID, S] {
	if b != nil {
		b.ForeignID = foreignID
	}
	return b
}

func (b *EntityBuilder[ID, S]) SetSchema(schema string) *EntityBuilder[ID, S] {
	if b != nil {
		b.Schema = schema
	}
	return b
}

func (b *EntityBuilder[ID, S]) SetVersion(version int) *EntityBuilder[ID, S] {
	if b != nil {
		b.Version = version
	}
	return b
}

func (b *EntityBuilder[ID, S]) SetNoDB(noDB *NoDBFieldsEntity) *EntityBuilder[ID, S] {
	if b != nil {
		b.NoDB = noDB
	}
	return b
}

func (b *EntityBuilder[ID, S]) SetName(name StringBasedType[S]) *EntityBuilder[ID, S] {
	if b != nil {
		b.Name = name
	}
	return b
}

func (b *EntityBuilder[ID, S]) SetSurname(surname StringBasedAlias) *EntityBuilder[ID, S] {
	if b != nil {
		b.Surname = surname
	}
	return b
}

func (b *EntityBuilder[ID, S]) SetValues(values []int32) *EntityBuilder[ID, S] {
	if b != nil {
		b.Values = values
	}
	return b
}

func (b *EntityBuilder[ID, S]) SetTs(ts []*time.Time) *EntityBuilder[ID, S] {
	if b != nil {
		b.Ts = ts
	}
	return b
}

func (b *EntityBuilder[ID, S]) SetVersioned(versioned sql_base.VersionedEntity) *EntityBuilder[ID, S] {
	if b != nil {
		b.Versioned = versioned
	}
	return b
}

func (b *EntityBuilder[ID, S]) SetChan(chan_ chan map[time.Time]string) *EntityBuilder[ID, S] {
	if b != nil {
		b.Chan = chan_
	}
	return b
}

func (b *EntityBuilder[ID, S]) SetSomeMap(someMap map[StringBasedType[string]]bytes.Buffer) *EntityBuilder[ID, S] {
	if b != nil {
		b.SomeMap = someMap
	}
	return b
}

func (b *EntityBuilder[ID, S]) SetEmbedded(embedded EmbeddedEntity) *EntityBuilder[ID, S] {
	if b != nil {
		b.Embedded = embedded
	}
	return b
}

func (b *EntityBuilder[ID, S]) SetOldForeignID(oldForeignID *ForeignIDAwareEntity[ID]) *EntityBuilder[ID, S] {
	if b != nil {
		b.OldForeignID = oldForeignID
	}
	return b
}

func (e *Entity[ID, S]) ToBuilder() *EntityBuilder[ID, S] {
	if e == nil {
		return &EntityBuilder[ID, S]{}
	}
	var (
		e_BaseEntity_ID                                              ID
		e_BaseEntity_be_RefCodeAwareEntity_rcae_CodeAwareEntity_Code string
		e_BaseEntity_be_ForeignIDAwareEntity_ForeignID               ID
	)
	if be := e.BaseEntity; be != nil {
		e_BaseEntity_ID = be.ID
		if rcae := be.RefCodeAwareEntity; rcae != nil {
			if cae := rcae.CodeAwareEntity; cae != nil {
				e_BaseEntity_be_RefCodeAwareEntity_rcae_CodeAwareEntity_Code = cae.Code
			}
		}
		e_BaseEntity_be_ForeignIDAwareEntity_ForeignID = be.ForeignIDAwareEntity.ForeignID
	}

	return &EntityBuilder[ID, S]{
		ID:           e_BaseEntity_ID,
		Code:         e_BaseEntity_be_RefCodeAwareEntity_rcae_CodeAwareEntity_Code,
		ForeignID:    e_BaseEntity_be_ForeignIDAwareEntity_ForeignID,
		Schema:       e.Metadata.Schema,
		Version:      e.Metadata.Version,
		NoDB:         e.NoDB,
		Name:         e.Name,
		Surname:      e.Surname,
		Values:       e.Values,
		Ts:           e.Ts,
		Versioned:    e.Versioned,
		Chan:         e.Chan,
		SomeMap:      e.SomeMap,
		Embedded:     e.Embedded,
		OldForeignID: e.OldForeignID,
	}
}
