// Code generated by 'fieldr'; DO NOT EDIT.

package stringify_enum

func (e EnumWithDuplicates) String() []string {
	switch e {
	case 0:
		return []string{"A"}
	case 1:
		return []string{"B"}
	case 2:
		return []string{"C", "D"}
	case 3:
		return []string{"F", "E"}
	default:
		return nil
	}
}
