// Code generated by 'fieldr'; DO NOT EDIT.

package stringify_enum

func (e Enum) String() string {
	switch e {
	case AA:
		return "AA"
	case BB:
		return "BB"
	case CC:
		return "CC"
	case DD:
		return "DD"
	default:
		return ""
	}
}

func EnumValues() []Enum {
	return []Enum{
		AA,
		BB,
		CC,
		DD,
	}
}

func EnumFromString(s string) (r Enum, ok bool) {
	ok = true
	switch s {
	case "AA":
		r = AA
	case "BB":
		r = BB
	case "CC":
		r = CC
	case "DD":
		r = DD
	default:
		ok = false
	}
	return
}
