// Code generated by 'fieldr'; DO NOT EDIT.

package stringify_enum

func (e Enum) String() string {
	switch e {
	case 1:
		return "AA"
	case 2:
		return "BB"
	case 3:
		return "CC"
	case 4:
		return "DC"
	default:
		return ""
	}
}
