// Code generated by 'fieldr'; DO NOT EDIT.

package stringify_enum

func (e EnumWithDuplicates) String() []string {
	switch e {
	case 1:
		return []string{"A"}
	case 2:
		return []string{"B"}
	case 3:
		return []string{"C"}
	case 4:
		return []string{"D", "E"}
	case 7:
		return []string{"G"}
	case 5:
		return []string{"F"}
	default:
		return nil
	}
}
