// Code generated by 'fieldr'; DO NOT EDIT.

package squirrel

type (
	entityTag          string
	entityTagValue     string
	entityTagValueList []entityTagValue
)

const (
	entityTagDb = entityTag("db")

	entityTagValueDbID      = entityTagValue("ID")
	entityTagValueDbName    = entityTagValue("NAME")
	entityTagValueDbSurname = entityTagValue("SURNAME")
	entityTagValueDbTs      = entityTagValue("TS")
)

var (
	entityTagValuesDb = entityTagValueList{entityTagValueDbID, entityTagValueDbName, entityTagValueDbSurname}
)

func (v *Entity) getFieldValuesByTag(tag entityTag) []interface{} {
	switch tag {
	case entityTagDb:
		return []interface{}{v.ID, v.Name, v.Surname}
	}
	return nil
}

func (v *Entity) getFieldValuesByTagDb() []interface{} {
	return []interface{}{v.ID, v.Name, v.Surname}
}

func (v entityTagValueList) strings() []string {
	strings := make([]string, len(v))
	for i, val := range v {
		strings[i] = string(val)
	}
	return strings
}
