// Code generated by 'fieldr'; DO NOT EDIT.

package squirrel

const (
	AlterColID      Col = "ID"
	AlterColName    Col = "NAME"
	AlterColSurname Col = "SURNAME"
)

func ACols() []Col {
	return []Col{AlterColID, AlterColName, AlterColSurname}
}
