// Code generated by 'fieldr'; DO NOT EDIT.

package new_opts

func NewEntity[ID any](opts ...func(*Entity[ID])) *Entity[ID] {
	r := &Entity[ID]{}
	for _, opt := range opts {
		opt(r)
	}
	return r
}

func WithID[ID any](iD ID) func(e *Entity[ID]) {
	return func(e *Entity[ID]) {
		m := e.Model
		if m == nil {
			m = new(Model[ID])
			e.Model = m
		}
		m.ID = iD
	}
}

func WithCreatedAt[ID any](createdAt int64) func(e *Entity[ID]) {
	return func(e *Entity[ID]) {
		m := e.Model
		if m == nil {
			m = new(Model[ID])
			e.Model = m
		}
		m.CreatedAt = createdAt
	}
}

func WithUpdatedAt[ID any](updatedAt int64) func(e *Entity[ID]) {
	return func(e *Entity[ID]) {
		m := e.Model
		if m == nil {
			m = new(Model[ID])
			e.Model = m
		}
		m.UpdatedAt = updatedAt
	}
}

func WithName[ID any](name string) func(e *Entity[ID]) {
	return func(e *Entity[ID]) {
		e.Name = name
	}
}
