// Code generated by 'fieldr'; DO NOT EDIT.

package enric_enum

func (e EnumWithDuplicates) String() []string {
	switch e {
	case 0:
		return []string{"A"}
	case 1:
		return []string{"B", "F"}
	case 2:
		return []string{"C"}
	default:
		return nil
	}
}

func EnumWithDuplicatesValues() []EnumWithDuplicates {
	return []EnumWithDuplicates{
		A,
		B,
		C,
		F,
	}
}
