// Code generated by 'fieldr'; DO NOT EDIT.

package enrich_enum

func (e EnumWithDuplicates) Name() []string {
	switch e {
	case A:
		return []string{"A"}
	case B:
		return []string{"B", "F"}
	case C:
		return []string{"C"}
	default:
		return nil
	}
}

func EnumWithDuplicatesAll() []EnumWithDuplicates {
	return []EnumWithDuplicates{
		A,
		B, //F
		C,
	}
}

func EnumWithDuplicatesByName(name string) (v EnumWithDuplicates, ok bool) {
	ok = true
	switch name {
	case "A":
		v = A
	case "B", "F":
		v = B
	case "C":
		v = C
	default:
		ok = false
	}
	return
}

func EnumWithDuplicatesByValue(value int) (e EnumWithDuplicates, ok bool) {
	ok = true
	switch value {
	case 0:
		e = A
	case 1:
		e = B
	case 2:
		e = C
	default:
		ok = false
	}
	return
}
