= Fieldr

== Fieldr

Generator of various enumerated constants, types, functions based on a type properties like name, structure fields, tags or base type nature.

=== Supported commands

* link:#fields-to-consts-example[fields-to-consts] - generate constants based on template applied to struct fields.
* link:#get-set-usage-example[get-set] - generates getters, setters for a structure type.
* link:#functional-options-constructor-example[new] - generates a function that creates an optionally initialized instance of the structure type.
* link:#full-constructor-example[new-full] - generates a function that creates a full initialized instance of the structure type.
* link:#builder-usage-example[builder] - generates builder API of a structure type.
* link:#as-map-usage-example[as-map] - generates a method or functon that converts the struct type to a map.
* link:#enrich-const-type-usage-example[enrich-const-type] - extends a constants type by 'get name' method, 'enum all values' function and 'get a constant by a value of the underlying type' function.

=== Installation

[source,console]
----
go install github.com/m4gshm/fieldr@latest
----
or
[source,console]
----
go install github.com/m4gshm/fieldr@HEAD
----

=== fields-to-consts example
source `entity.go`:

[source,go]
----
include::../examples/usage/enum_const/entity.go[]
----

then running this command in the same directory:
[source,console]
----
go generate .
----
will be generated `entity_fieldr.go` file with the next content:

[source,go]
----
include::../examples/usage/enum_const/entity_fieldr.go[]
----

this consist of constants based on the `json` tag contents and the method `jsons` that enumerates these constants.

To get extended help of the command, use the following:

[source,console]
----
fieldr fields-to-consts help
----

==== Example of generating ORM elements: 

source `entity.go`:
[source,go]
----
include::../examples/usage/enum_const/enum_const_db/entity.go[]
----

generated `entity_fieldr.go`:

[source,go]
----
include::../examples/usage/enum_const/enum_const_db/entity_fieldr.go[]
----

===== explanation of used args:
- -name _"'col' + field.name"_ - defines constant names as 'col' appended by the associated field name.
- -val _"tag.db"_ - defines the value of a constant as a copy of the `db` tag of the associated field name.
- -flat _Versioned_ - also uses the `VersionedEntity` fields as constants source type in addition to the base `Entity` type.
- -type _column_ - adds the `column` type, and uses it as the type of the generated constants.
- -list _._ - generates the `columns` function that returns constant values. It can be used to build sql queries like INSERT, SELECT.
- -ref-access _._ - generates the `ref` method that provides access to the filed values, returns a reference pointing to the field associated with the constant. The method can be used in conjunction with Row.Scan from sql package.
- -include _"tag.pk != nil"_ - uses only 'pk' tag having a value.


=== get-set usage example

source `entity.go`

[source,go]
----
include::../examples/usage/get_set/entity.go[]
----

[source,console]
----
go generate .
----
generates `entity_fieldr.go`

[source,go]
----
include::../examples/usage/get_set/entity_fieldr.go[]
----

=== 'Functional Options' constructor example 

source `entity.go`

[source,go]
----
include::../examples/usage/new_opts/entity.go[]
----

[source,console]
----
go generate .
----
generates `entity_fieldr.go`

[source,go]
----
include::../examples/usage/new_opts/entity_fieldr.go[]
----

=== Full constructor example 

source `entity.go`

[source,go]
----
include::../examples/usage/new_full/entity.go[]
----

[source,console]
----
go generate .
----
generates `entity_fieldr.go`

[source,go]
----
include::../examples/usage/new_full/entity_fieldr.go[]
----

=== builder usage example

source `entity.go`

[source,go]
----
include::../examples/usage/builder/entity.go[]
----

[source,console]
----
go generate .
----
generates `entity_fieldr.go`

[source,go]
----
include::../examples/usage/builder/entity_fieldr.go[]
----

=== as-map usage example

source `struct.go`

[source,go]
----
include::../examples/asmap/struct.go[]
----

[source,console]
----
go generate .
----
generates two files `struct_as_map.go`, `address_as_map.go`

[source,go]
----
include::../examples/asmap/struct_as_map.go[]
----
[source,go]
----
include::../examples/asmap/address_as_map.go[]
----

=== enrich-const-type usage example
source `enum.go`

[source,go]
----
include::../examples/usage/enrich_enum/enum.go[]
----

[source,console]
----
go generate .
----
generates `enum_fieldr.go`

[source,go]
----
include::../examples/usage/enrich_enum/enum_fieldr.go[]
----

and `stringenum_fieldr.go`

[source,go]
----
include::../examples/usage/enrich_enum/stringenum_fieldr.go[]
----


See more examples link:./internal/examples/[here]


