// Code generated by 'fieldr'; DO NOT EDIT.

package gorm

const (
	entityTagValueGormID        = "ID"
	entityTagValueGormName      = "NAME"
	entityTagValueGormSurname   = "SURNAME"
	entityTagValueGormUpdatedAt = "UPDATED_AT"
)
