// Code generated by 'fieldr'; DO NOT EDIT.

package asmap

type EmbeddedAddressField string

const (
	ZipCode     EmbeddedAddressField = "ZipCode"
	AddressLine EmbeddedAddressField = "AddressLine"
)

func (e *EmbeddedAddress) AsMap() map[EmbeddedAddressField]any {
	if e == nil {
		return nil
	}
	m := map[EmbeddedAddressField]any{}
	m[ZipCode] = e.ZipCode
	m[AddressLine] = e.AddressLine
	return m
}
