// Code generated by 'fieldr'; DO NOT EDIT.

package new_opt

func NewEntity[ID any](
	ID_ ID,
	opts ...func(*Entity[ID]),
) *Entity[ID] {
	r := &Entity[ID]{
		Model: &Model[ID]{
			ID: ID_,
		},
	}
	for _, opt := range opts {
		opt(r)
	}
	return r
}

func WithCreatedAt[ID any](createdAt int64) func(e *Entity[ID]) {
	return func(e *Entity[ID]) {
		m := e.Model
		if m == nil {
			m = new(Model[ID])
			e.Model = m
		}
		m.CreatedAt = createdAt
	}
}

func WithUpdatedAt[ID any](updatedAt int64) func(e *Entity[ID]) {
	return func(e *Entity[ID]) {
		m := e.Model
		if m == nil {
			m = new(Model[ID])
			e.Model = m
		}
		m.UpdatedAt = updatedAt
	}
}

func WithName[ID any](name string) func(e *Entity[ID]) {
	return func(e *Entity[ID]) {
		e.Name = name
	}
}
