// Code generated by 'fieldr'; DO NOT EDIT.

package new_full

import (
	"bytes"
	"example/sql_base"
	"time"
)

func NewEntity[ID any](
	E *E[ID],
	metadata struct {
		Schema  string
		Version int
	},
	NoDB NoDBFieldsEntity,
	name StringBasedType[string],
	surname StringBasedAlias,
	Values []int32,
	Ts []*time.Time,
	versioned sql_base.VersionedEntity,
	channel chan map[time.Time]string,
	someMap map[StringBasedType[string]]bytes.Buffer,
	Embedded EmbeddedEntity,
	OldForeignID *foreignIDAwareEntity[ID],
) *Entity[ID] {
	return &Entity[ID]{
		E:            E,
		metadata:     metadata,
		NoDB:         NoDB,
		name:         name,
		surname:      surname,
		Values:       Values,
		Ts:           Ts,
		versioned:    versioned,
		channel:      channel,
		someMap:      someMap,
		Embedded:     Embedded,
		OldForeignID: OldForeignID,
	}
}
