// Code generated by 'fieldr'; DO NOT EDIT.

package new_full

func NewCodeAware(
	emptyInlined *emptyInlined,
	code string,
) *CodeAwareEntity {
	return &CodeAwareEntity{
		emptyInlined: emptyInlined,
		Code:         code,
	}
}
