// Code generated by 'fieldr'; DO NOT EDIT.

package json

type structJson string

const (
	structJsonID      structJson = "id"
	structJsonName    structJson = "name,omitempty"
	structJsonSurname structJson = "surname,omitempty"
	structJsonNoTag   structJson = "NoTag"
)

func structJsons() []structJson {
	return []structJson{
		structJsonID,
		structJsonName,
		structJsonSurname,
		structJsonNoTag,
	}
}

func (c structJson) field() string {
	switch c {
	case structJsonID:
		return "ID"
	case structJsonName:
		return "Name"
	case structJsonSurname:
		return "Surname"
	case structJsonNoTag:
		return "NoTag"
	}
	return ""
}

func (c structJson) val(s *Struct) interface{} {
	switch c {
	case structJsonID:
		return s.ID
	case structJsonName:
		return s.Name
	case structJsonSurname:
		return s.Surname
	case structJsonNoTag:
		return s.NoTag
	}
	return nil
}
