// Code generated by 'fieldr'; DO NOT EDIT.

package builder

type EntityBuilder[ID any] struct {
	iD        ID
	createdAt int64
	updatedAt int64
	name      string
}

func NewEntityBuilder[ID any]() *EntityBuilder[ID] {
	return &EntityBuilder[ID]{}
}

func (b *EntityBuilder[ID]) Build() *Entity[ID] {
	if b == nil {
		return &Entity[ID]{}
	}
	return &Entity[ID]{
		Model: &Model[ID]{
			ID:        b.iD,
			CreatedAt: b.createdAt,
			UpdatedAt: b.updatedAt,
		},
		Name: b.name,
	}
}

func (b *EntityBuilder[ID]) ID(iD ID) *EntityBuilder[ID] {
	if b != nil {
		b.iD = iD
	}
	return b
}

func (b *EntityBuilder[ID]) CreatedAt(createdAt int64) *EntityBuilder[ID] {
	if b != nil {
		b.createdAt = createdAt
	}
	return b
}

func (b *EntityBuilder[ID]) UpdatedAt(updatedAt int64) *EntityBuilder[ID] {
	if b != nil {
		b.updatedAt = updatedAt
	}
	return b
}

func (b *EntityBuilder[ID]) Name(name string) *EntityBuilder[ID] {
	if b != nil {
		b.name = name
	}
	return b
}

func (i *Entity[ID]) ToBuilder() *EntityBuilder[ID] {
	if i == nil {
		return &EntityBuilder[ID]{}
	}
	var i_Model_ID ID
	if i.Model != nil {
		i_Model_ID = i.Model.ID
	}
	var i_Model_CreatedAt int64
	if i.Model != nil {
		i_Model_CreatedAt = i.Model.CreatedAt
	}
	var i_Model_UpdatedAt int64
	if i.Model != nil {
		i_Model_UpdatedAt = i.Model.UpdatedAt
	}

	return &EntityBuilder[ID]{
		iD:        i_Model_ID,
		createdAt: i_Model_CreatedAt,
		updatedAt: i_Model_UpdatedAt,
		name:      i.Name,
	}
}
