// Code generated by 'fieldr'; DO NOT EDIT.

package builder

type EntityBuilder struct {
	id   int
	name string
}

func (b EntityBuilder) Build() *Entity {
	return &Entity{
		Id:   b.id,
		Name: b.name,
	}
}

func (b *EntityBuilder) Id(id int) *EntityBuilder {
	b.id = id
	return b
}

func (b *EntityBuilder) Name(name string) *EntityBuilder {
	b.name = name
	return b
}

func (i *Entity) ToBuilder() *EntityBuilder {
	return &EntityBuilder{
		id:   i.Id,
		name: i.Name,
	}
}
