= Fieldr

== Fieldr

Generator of various enumerated constants, types, functions based on structure fields and their tags.

=== Supported commands

* get-set - generates getters, setters for a structure type.
* builder - generates builder API of a structure type.
* enum-const - generate constants based on template applied to struct fields.
* as-map - generates method or functon that converts the struct type to a map.

=== Installation

[source,console]
----
go install github.com/m4gshm/fieldr@latest
----
or
[source,console]
----
go install github.com/m4gshm/fieldr@HEAD
----

=== Get-set usage example

source `entity.go`

[source,go]
----
include::../examples/usage/get_set/entity.go[]
----

[source,console]
----
go generate .
----
generated `entity_fieldr.go`

[source,go]
----
include::../examples/usage/get_set/entity_fieldr.go[]
----

=== Builder usage example

source `entity.go`

[source,go]
----
include::../examples/usage/builder/entity.go[]
----

[source,console]
----
go generate .
----
generated `entity_fieldr.go`

[source,go]
----
include::../examples/usage/builder/entity_fieldr.go[]
----

=== Enum constant example
source `entity.go`:

[source,go]
----
include::../examples/usage/enum_const/entity.go[]
----

then running this command in the same directory:
[source,console]
----
go generate .
----
will be generated `entity_fieldr.go` file with the next content:

[source,go]
----
include::../examples/usage/enum_const/entity_fieldr.go[]
----

this consist of constants based on the `json` tag contents and the method `jsons` that enumerates these constants.

To get extended help of the command, use the following:

[source,console]
----
fieldr enum-const --help
----

=== As-map usage example

source `struct.go`

[source,go]
----
include::../examples/asmap/struct.go[]
----

[source,console]
----
go generate .
----
will be generate two files `struct_as_map.go`, `address_as_map.go`

[source,go]
----
include::../examples/asmap/struct_as_map.go[]
----
[source,go]
----
include::../examples/asmap/address_as_map.go[]
----




See more examples link:./examples/[here]


